name: reviewdog
on: [pull_request]

jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: shogo82148/action-golangci-lint@d9f6c3a4f68bced7466cd07b5d3aad6be6b8486e
        with:
          github_token: ${{ secrets.github_token }}
          level: warning
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          path: "."
          pattern: "*.sh"
          exclude: "./.git/*"
